services:
  exporter:
    container_name: exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      LOG_LEVEL: debug
      POWERDNS_API_KEY: sampleapikey
    ports:
      - "8080:8080"
    command: /bin/powerdns-exporter --host 0.0.0.0 --port 8080 --powerdns-webserver-host pdns --powerdns-webserver-port 8081

  pdns:
    image: powerdns/pdns-auth-master:latest
    container_name: pdns
    environment:
      - PDNS_API_KEY=sampleapikey
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "8081:8081"
    volumes:
      - ./development/powerdns/pdns.conf:/etc/powerdns/pdns.conf   # pdns.confファイルをコンテナにマウント
      - pdns-data:/var/lib/powerdns  # データ用のボリューム（オプション）
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./development/mysql/entrypoint.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  pdns-data:   # 必要であれば、データ用のボリューム
  mysql-data:
